services:
cowrie:
    image: cowrie/cowrie:latest
    container_name: cowrie
    restart: unless-stopped
    ports:
            - "2222:2222"
    volumes:
            - ./cowrie-logs:/cowrie/cowrie-git/var/log/cowrie
            - ./cowrie-data:/cowrie/cowrie-git/var/lib/cowrie
